version: "3"
networks:
  innernet:
    driver: bridge
    name: innernet

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - innernet
    ports:
      - "2181:2181"
  kafkaserver:
    image: wurstmeister/kafka
    container_name: kafkaserver
    hostname: kafkaserver
    depends_on:
      - zookeeper
    networks:
      - innernet
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      ADVERTISED_HOST: host.docker.internal
      ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_PORT: 9092
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafkaserver
    networks:
      - innernet
    ports:
      - "8888:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaserver:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181